app/models.py
from datetime import datetime
from app import db
from sqlalchemy import ForeignKey, DateTime

class Tattoo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(), nullable=False)
    image = db.Column(db.String(), nullable=False)

    def __repr__(self):
        return f"Tattoo {self.name} has been uploaded"


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(), nullable=False)
    content = db.Column(db.String(), nullable=False)
    image = db.Column(db.String(), nullable=False)

    def __repr__(self):
        return f"Post {self.title} has been uploaded"


class Admin(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(), nullable=False)
    email = db.Column(db.String(), nullable=False)
    password = db.Column(db.String(), nullable=False)

    def __repr__(self):
        return f"Tattoo {self.name} has been uploaded"


class FormRequests(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(), nullable=False)
    content = db.Column(db.String(), nullable=False)
    date = db.Column(db.DateTime(), default=datetime.utcnow)

app/admins/forms.py
from ast import In
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField
from flask_ckeditor import CKEditorField
from flask_wtf import FlaskForm
from wtforms.validators import InputRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[InputRequired()])
    content = CKEditorField('Content')
    image = FileField('Upload a post picture', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Save')


class TattooForm(FlaskForm):
    name = StringField('Name', validators=[InputRequired()])
    image = FileField('Upload a tattoo picture', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Upload')

app/main/forms.py
from wtforms import StringField, TextAreaField, SubmitField
from flask_wtf import FlaskForm
from wtforms.validators import InputRequired

class ContactForm(FlaskForm):
    title = StringField('Title', validators=[InputRequired()])
    content = TextAreaField('Content', validators=[InputRequired()])
    submit = SubmitField('Send')

app/__init__.py
from flask import Flask, jsonify, render_template
from flask_sqlalchemy import SQLAlchemy
from app.config import Config
from flask_ckeditor import CKEditor

db = SQLAlchemy()
ckeditor = CKEditor()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)
    ckeditor.init_app(app)

    db.init_app(app)

    from app.main.routes import main
    from app.admins.routes import admins
    from app.errors.handlers import errors

    app.register_blueprint(main)
    app.register_blueprint(admins)
    app.register_blueprint(errors)

    @app.errorhandler(400)
    def unprocessable_entity(error):
        return render_template("/errors/400.html")

    @app.errorhandler(401)
    def unauthorized(error):
        return render_template("/errors/401.html")

    @app.errorhandler(403)
    def forbidden(error):
        return render_template("/errors/403.html")

    @app.errorhandler(404)
    def not_found(error):
        return render_template("/errors/404.html")

    @app.errorhandler(500)
    def internal_server_error(error):
        return render_template("/errors/500.html")

    return app

app/admins/routes.py
from crypt import methods
from flask import redirect, url_for, render_template,request, flash, Blueprint
from app import db
from app.models import Tattoo, Post
from app.admins.forms import PostForm, TattooForm
from app.admins.utils import save_picture

admins = Blueprint("admins", __name__)

@admins.route('/admin')
def admin_home():
    return render_template('admin_layout.html')


@admins.route('/create_post', methods=['GET', 'POST'])
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        image_file=save_picture(form.image.data)
        post = Post(title=form.title.data, content=form.content.data, 
        image=image_file)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for("admins.admin_home"))
    return render_template("create_post.html", form=form)


@admins.route('/create_tattoo', methods=['POST', 'GET'])
def create_tattoo():
    form = TattooForm()
    if form.validate_on_submit():
        if form.image.data:
            image_file = save_picture(form.image.data)
            tattoo = Tattoo(name=form.name.data, image=image_file)
            db.session.add(tattoo)
            db.session.commit()
            flash("Tattoo has been successfully uploaded", "success")
        return redirect(url_for("admins.create_tattoo"))
    return render_template("create_tattoo.html", form=form)

app/main/routes.py
from flask import Blueprint, jsonify, url_for, render_template, request, redirect, flash
from app.models import Tattoo, FormRequests
from app.main.forms import ContactForm
from app import db

main = Blueprint("main", __name__)

@main.route('/')
@main.route('/home')
def home():
    return render_template("home.html", title="Home")


@main.route('/some-fe')
def some_fe():
    return jsonify({
        "content":"this is some repsonse"
    })


@main.route('/about-us')
def about():
    return render_template('about.html',title="About Us")


@main.route('/gallery')
def gallery():
    tattoos = Tattoo.query.all()
    urls = []
    for tattoo in tattoos:
        url = url_for('static', filename="images/"+tattoo.image)
        urls.append(url)
    return render_template('gallery.html', title="Gallery", urls=urls)


@main.route('/contact-us', methods=['GET', 'POST'])
def contact():
    form = ContactForm()
    if form.validate_on_submit():
        new_request = FormRequests(title=form.title.data, content=form.content.data)
        db.session.add(new_request)
        db.session.commit()
        flash('Your request has been successfully submitted', 'success')
        return redirect(url_for('main.home'))
    return render_template('contact.html', title="Contact Us", form=form)

app/templates/about.html
{% extends 'layout.html' %}

{% block container %}
<div class="col-10 text-white pt-5 mx-auto text-justify mb-5">

    <div class="container mt-5 mb-5 mx-auto">
        <div class="img-container mx-auto col-12 my-4">
            <img src="{{url_for('static', filename='images/gallery_2.jpg')}}" alt="" class="responsive img-thumbnail">
        </div>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores magni veniam ab inventore dolor repudiandae nam cupiditate asperiores sed dolore architecto illo possimus porro libero voluptatem ratione rem, doloribus reprehenderit hic animi. Optio harum quo quos veritatis, dolores, natus, reprehenderit accusantium temporibus cumque ducimus sed! Mollitia molestiae ullam eum exercitationem asperiores deleniti accusantium suscipit consectetur voluptatibus? Corrupti sit laudantium deserunt eveniet provident vitae dignissimos rem, repudiandae adipisci. Quam, voluptatum sunt. Numquam facilis est saepe? Fugit, facilis soluta maxime vel necessitatibus corrupti animi amet beatae quod quos nam alias ratione. Sunt, odio possimus esse autem non perferendis provident et totam minus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit temporibus quas illo quaerat nostrum ducimus eligendi, velit, earum harum molestias ea. In nisi odio consequuntur laborum illum impedit magnam accusantium unde sit officia dolores nam dolorem obcaecati enim eos voluptas dignissimos veritatis, corporis quibusdam atque. Soluta blanditiis fuga ut architecto vel aut maiores accusantium officia explicabo. Iste quasi possimus minus repellendus architecto sunt? Quos at cupiditate dolorum modi accusantium sint non expedita quod, blanditiis id, facere tempore maxime vel laboriosam consequuntur mollitia illo voluptatibus voluptatem quae quas, unde ea. Possimus sint at quas ab nobis veniam cupiditate nulla, ipsum voluptate.
    </div>
</div>

{% endblock %}

app/templates/admin_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Andada+Pro&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/index.css')}}">
    {% if title %}
        <title>Tattoo Artist - {{title}}</title>
    {% else %}
        <title>Tattoo Artist</title>
    {% endif %}
</head>
<body class="bg-dark">
    <header class="border-bottom border-secondary">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="/">Tattoo Artist</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">                   
                    <div class="navbar-nav mr-auto navbar-right">
                        <a class="nav-item nav-link font-weight-bold text-white ml-2" href="{{ url_for('admins.create_post') }}">Post</a>
                        <a class="nav-item nav-link font-weight-bold text-white ml-2" href="{{ url_for('admins.create_tattoo') }}">Tattoo</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>  

    <div class="pt-5">
        <div class="mt-5">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                <div class=" mt-5 alert alert-{{ category }} alert-dismissible fade show" role="alert" id="flashed_messages">
                    {{message}}
                    <button type="button" class="close test-white" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        </div>        
    </div>
    
    {% block container %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

app/templates/contact.html
{% extends 'layout.html' %}

{% block container %}

<div class="row w-100 m-auto d-flex justify-content-center" style="height:85vh">
    <div class="col-lg-8 mt-5">
        <form action="" method="POST" enctype="multipart/form-data" class="text-white d-flex justify-content-center">
            {{form.hidden_tag()}}
            <div class="col-xl-10">
                <div>
                    {{form.title(class="col-12 mt-5")}}
                </div>
                <div class="my-3">
                    {{form.content(class="col-12", rows=15)}}
                </div>
                <div class="d-flex justify-content-between my-3">
                    {{form.submit(class="col-2")}}                
                </div>
            </div>
        </form>
    </div>    
</div>


{% endblock %}

app/templates/create_post.html
{% extends 'admin_layout.html' %}

{% block container %}
<div class="row w-100 m-auto d-flex justify-content-center">
    <div class="col-lg-8 mt-5">
        <form action="" method="POST" enctype="multipart/form-data" class="text-white d-flex justify-content-center">
            {{form.hidden_tag()}}
            <div class="col-xl-10">
                <div>
                    {{form.title(class="col-12 mt-5")}}
                </div>
                <div class="my-3">
                    {{form.content()}}
                </div>
                <div class="d-flex justify-content-between my-3">
                    {{form.image}}    
                    {{form.submit(class="col-2")}}                
                </div>
            </div>
        </form>
        {{ ckeditor.load() }}
        {{ ckeditor.config(name='content') }}
    </div>    
</div>


{% endblock %}

app/templates/create_tattoo.html
{% extends 'admin_layout.html' %}

{% block container %}
<div class="container w-50 mx-auto d-flex justify-content-center">
    <div class="col-lg-8 mt-5">
        <form action="" method="POST" enctype="multipart/form-data" class="text-white d-flex justify-content-center">
            {{form.hidden_tag()}}
            <div class="col-xl-10 mt-5">
                
                <div class="my-3">
                    {{form.name.label}}: {{form.name()}}
                </div>
                <div class="d-flex justify-content-between my-3">
                    {{form.image()}}    
                </div>
                <div class="d-flex justify-content-between my-3">
                    {{form.submit(class="col-3")}}                
                </div>
            </div>
        </form>
    </div>    
</div>


{% endblock %}

app/templates/gallery.html
{% extends 'layout.html' %}

{% block container %}
<div class="container-fluid d-flex flex-wrap justify-content-start  pt-5 pb-5">

{% for url in urls %}
<div class="img-container col-xl-4 my-4">
    <img src="{{url}}" alt="" class="responsive img-thumbnail">
</div>
{% endfor %}
</div>

   

{% endblock %}

app/templates/home.html
{%  extends 'layout.html' %}

{% block container %}
<div class="home-background"></div>
<div class="book-button-container">
        <a href="{{ url_for('main.contact') }}" class="text-white font-weight-bold btn btn-dark p-3 px-5 mb-5" style="position: fixed; top:50%">Book Now</a>
</div>  
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Andada+Pro&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/index.css')}}">
    {% if title %}
        <title>Tattoo Artist - {{title}}</title>
    {% else %}
        <title>Tattoo Artist</title>
    {% endif %}
</head>
<body class="bg-dark">
    
    <header class="border-bottom border-secondary">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="/">Tattoo Artist</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">                   
                    <div class="navbar-nav mr-auto navbar-right">
                        {% if title != "Home" %}
                        <a class="nav-item nav-link font-weight-bold text-white ml-2" href="{{ url_for('main.home') }}">Home</a>
                        {% endif %}
                        {% if title != "About Us" %}
                        <a class="nav-item nav-link font-weight-bold text-white ml-2" href="{{ url_for('main.about') }}">About Us</a>
                        {% endif %}
                        {% if title != "Gallery" %}
                        <a class="nav-item nav-link font-weight-bold text-white ml-2" href="{{ url_for('main.gallery') }}">Gallery</a>
                        {% endif %}
                        {% if title != "Contact Us" %}
                        <a class="nav-item nav-link font-weight-bold text-white ml-2" href="{{ url_for('main.contact') }}">Contact Us</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="pt-5">
        <div class="mt-5">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                <div class=" mt-5 alert alert-{{ category }} alert-dismissible fade show" role="alert" id="flashed_messages">
                    {{message}}
                    <button type="button" class="close test-white" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        </div>        
    </div>
  
    {% block container %}{% endblock %}
    <footer class="border-top border-secondary">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <div class="d-flex flex-column justify-content-center navbar-nav m-auto flex-w">
                    <div class="text-white mx-5">X Tattoo Studio</div>
                </div>
                <div class="d-flex flex-column justify-content-center navbar-nav m-auto">
                    <div class="text-white mx-5">2022</div>
                </div>
                <div class="d-flex flex-column justify-content-center navbar-nav m-auto">
                    <div class="text-white mx-5">Designed by Kemal Pehlivan</div>
                </div>
        </nav>
    </footer>
    <script src="{{url_for('static', filename='script/jquery.js')}}"></script>
    <script src="{{url_for('static', filename='script/index.js')}}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>